cadastro/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.base, name='base'),
    path('lista/', views.listar_usuarios, name='listar_usuarios'),
    path('novo/', views.criar_usuario, name='criar_usuario'),
    path('editar/<int:pk>/', views.editar_usuario, name='editar_usuario'),
    path('excluir/<int:pk>/', views.excluir_usuario, name='excluir_usuario'),
    path('home/',views.homelider, name='home_lider'),

    
   
]
   
   

meu_projeto/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cadastro.urls')),
]

cadastro/models.py
from django.db import models

class Usuario(models.Model):
    nome = models.CharField(max_length=100)
    data_nascimento = models.DateField()
    cpf = models.CharField(max_length=12)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=20)
    cep = models.CharField(max_length=12)
    uf = models.CharField(max_length=20)
    bairro = models.CharField(max_length=20)
    rua = models.CharField(max_length=100)
    numero = models.CharField(max_length=10)
    complemento = models.CharField(max_length=100, blank=True, null=True)
    telefone = models.CharField(max_length=20, blank=True, null=True)
    tipoUsuario = models.CharField(max_length=20)
  
    

    
    
    

    
 
    
    def __str__(self):
        return self.nome
    
    

cadastro/forms.py
from django import forms
from .models import Usuario

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = [ 'nome', 'data_nascimento', 'cpf', 'email', 'password', 'cep', 'uf', 'bairro', 'rua', 'numero',
                  'complemento', 'telefone','tipoUsuario']

cadastro/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Usuario
from .forms import UsuarioForm


def homelider(request):
    return render(request, 'home.html')

def base(request):
    return render(request, 'cadastro/base.html')


def listar_usuarios(request):
    usuarios = Usuario.objects.all()
    return render(request, 'cadastro/listar_usuarios.html',{'usuarios': usuarios})

def criar_usuario(request):
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            return redirect('listar_usuario')
    else:
        form = UsuarioForm()
    return render(request, 'cadastro/criar_usuario.html', {'form': form})


def editar_usuario(request, pk):
    usuario = get_object_or_404(Usuario, pk=pk)
    if request.method == 'POST':
        form = UsuarioForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('listar_usuario')
        else:
            form = UsuarioForm(instance=usuario)
            return render(request, 'cadastro/editar_usuario.html',{'form': form})
        
        
def excluir_usuario(request, pk):
    usuario = get_object_or_404(Usuario, pk=pk)
    usuario.delete()
    return redirect('listar_usuario')
        
        
        

cadastro/templates/cadastro/base.html
<!DOCTYPE html>


<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Raízes da Educação</title>
    
    {% load static %}
    <!-- Usando a tag Django static para o favicon -->
    <link rel="icon" href="{% static 'img/logo.png' %}">
    <!-- Usando a tag Django static para o CSS -->
    <link rel="stylesheet" href="{% static 'cadastro/style.css' %}">
</head>
<body>
    <header class="superfície">
        <div class="interface">
            <div class="logo">
               <a href="#"> <img src="{% static 'img/logo.png' %}" alt="Logo da Raízes da Educação"></a>
            </div>

            <nav class="menu-desktop">
                <ul>
                    <a href="/">Home</a>
                    <a href="#">Quem Somos</a>
                    <a href="#">Cursos</a>
                    <a href="/novo">Cadastre-se</a>
                    <a href="#">Login</a>
                </ul>
            </nav>
        </div><!--interface-->
    </header>
    
    <main>
        <section class="topo-do-site">
            <div class="interface">
                <div class="flex">

                    <div class="txt-topo-site">
                        <div class="pincel">
                            <!-- Usando a tag Django static para as imagens -->
                            <img src="{% static 'img/pincelhome.png' %}" alt="">
                        </div>

                        <div class="arvores">
                            <img src="{% static 'img/arvores.png' %}" alt="">
                        </div>
                        <div class="letreirohome">
                            <img src="{% static 'img/efeitoletreiro.png' %}" alt="">
                            <p>Educação Muda vidas, se inscreva no nosso site para você mudar sua vida através da educação.</p>
                            <button><a href="/novo">Cadastre-se</a></button>
                        </div>
                    </div>
                    <div class="detalhe">
                        <img src="{% static 'img/detalhehome1.png' %}" alt="">
                    </div>

                    <div class="img-topo-site">
                        <img src="{% static 'img/home.png' %}" alt="">
                    </div>

                </div><!--flex-->
            </div><!--interface-->
        </section>

        <section class="missao-visao-valores">
            <div class="interface">
                <!-- Usando a tag Django static para a imagem -->
                <img class="logo1" src="{% static 'img/LogoSessaoMissaoValores.png' %}" alt="">
            
            <div class="flex">

                <div class="box">

                <div class="card1">
                    <h2>Valores: </h2>
                    <i> <img src="{% static 'img/flag-fill.svg' %}" alt=""></i>
                    <p>Transparência, equidade, respeito, compromisso, hospitalidade, ética, qualidade!</p>
                    <img class="detalhe" src="{% static 'img/iconcard.png' %}" alt="">
                    
                </div>
                <div class="card1">
                    <h2>Missão: </h2>
                    <i> <img src="{% static 'img/star-fill.svg' %}" alt=""></i>
                    <p>Contribuir com o aprendizado e a formação de pessoas que não tiveram a oportunidade de ter uma boa educação escolar para jovens e adultos.</p>
                    <img class="detalhe" src="{% static 'img/iconcard.png' %}" alt="">
                </div>
                <div class="card1">
                    <h2>Visão: </h2>
                    <i> <img src="{% static 'img/eye-fill.svg' %}" alt=""></i>
                    <p>Inovar o modelo de ensino e tornar acessível um bom ensino presencial. Transformar a vida de jovens e adultos com um modelo de ensino acessível e inovador.</p>
                    <img class="detalhe" src="{% static 'img/iconcard.png' %}" alt="">
                </div>
            </div>
            </div><!--flex-->
        </div><!--interface-->
        </section>

        <section class="quemSomos">
            <div class="interface">
                <h2>Quem Somos</h2>
                <div class="flex">

                    <div class="imgQuemSomos">
                        <img src="{% static 'img/imgquemsomos.png' %}" alt="">
                    </div>
                    <div class="txt-quem-somos">
                        <p>Uma plataforma que conecta estudantes a sala de aulas com instrutores e conforto para o melhor aprendizado, levando conhecimento, capacitação e uma ótima qualidade de ensino para certificar pessoas na leitura e nos aprendizados básicos.</p>
                        <button><a href="#">Cadastre-se</a></button>
                    </div>
                </div><!--flex-->
            </div><!--interface-->
        </section>
    </main>

    <footer>
        <div class="interface">
            <div class="flex">
                <div> <img src="{% static 'img/plantinhafooter.png' %}" alt=""></div>
                <div class="logo-footer"> <img src="{% static 'img/logo.png' %}" alt=""></div>
                <div> <img src="{% static 'img/plantinhafooter.png' %}" alt=""></div>
            </div><!--flex-->
        </div><!--interface-->
    </footer>
</body>
</html>

cadastro/templates/cadastro/criar_usuario.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Raízes da Educação</title>
  
    {% load static %}
    <link rel="icon" href="{% static 'img/logo.png' %}">
    <link rel="stylesheet" href="{% static 'cadastro/cadastro.css' %}"> 
</head>
<body>

    <header>
        <div class="interface">
            <div class="logo">
               <a href="#"> <img src="{% static 'img/logo.png' %}" alt="Logo da Raízes da Educação"></a>
            </div>

            <nav class="menu-desktop">
                <ul>
                    <a href="#">Home</a>
                    <a href="#">Quem Somos</a>
                    <a href="#">Cursos</a>
                    <a href="#">Cadastre-se</a>
                    <a href="#">Login</a>
                </ul>
            </nav>
        </div><!--interface-->
    </header>

<main>
<section class="form-sect">

    
    {% block title %}{% endblock %}
    
    {% block content %}
    <h1>{% if form.instance.pk %}{% else %}{% endif %} </h1>
    <form method="post">
        {% csrf_token %}
        
     
       <h2>Cadastre-se</h2>
        <div class="form-group">
            <label for="id_nome">Nome: </label>
            {{ form.nome }}
        </div>
        
        
        <div class="form-group">
            <label for="id_data_nascimento">Data de Nascimento:</label>
            {{ form.data_nascimento }}
        </div>
        
        
        <div class="form-group">
            <label for="id_cpf">CPF:</label>
            {{ form.cpf }}
        </div>
        
        
        <div class="form-group">
            <label for="id_email">Email:</label>
            {{ form.email }}
        </div>

      
        <div class="form-group" id="senha">
            <label for="id_password">Senha:</label>
            {{ form.password }}
        </div>
        
        
        <div class="form-group">
            <label for="id_cep">CEP:</label>
            {{ form.cep }}
        </div>
        
        
        <div class="form-group">
            <label for="id_uf">UF</label>
            <input type="text" id="id_uf" name="uf" class="form-control" readonly>
        </div>
        
        
        <div class="form-group">
            <label for="id_bairro">Bairro:</label>
            <input type="text" id="id_bairro" name="bairro" class="form-control" readonly>
        </div>
        
        
        <div class="form-group">
            <label for="id_rua">Rua:</label>
            <input type="text" id="id_rua" name="rua" class="form-control" readonly>
        </div>
        
        
        <div class="form-group">
            <label for="id_numero">Número:</label>
            {{ form.numero }}
        </div>
        
        
        <div class="form-group">
            <label for="id_complemento">Complemento:</label>
            {{ form.complemento }}
        </div>
        
        
        <div class="form-group">
            <label for="id_telefone">Telefone:</label>
            {{ form.telefone }}
        </div>
        <div class="tipo">
            <label for="{{ form.tipoUsuario.id_for_label }}">Escolha uma opção:</label> 
            <select name="tipoUsuario" id="id_tipoUsuario">
                <option value="A" selected>Aluno</option>
                <option value="B">Instituição</option>
                <option value="C">Professor</option>
                <option value="D">Líder Comunitário</option>
            </select>  <!-- Gera o select para 'tipoUsuario' -->
        </div>
        
  
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Cadastre-se</button>
        </div>
       
    </section>

    </form>
</main>

   


    


<footer>
    <div class="interface">
        <div class="flex">
            <div> <img src="{% static 'img/plantinhafooter.png' %}" alt=""></div>
            <div class="logo-footer"> <img src="{% static 'img/logo.png' %}" alt=""></div>
            <div> <img src="{% static 'img/plantinhafooter.png' %}" alt=""></div>
        </div><!--flex-->
    </div><!--interface-->
</footer>


<script src="{% static 'js/ajax.js' %}"></script>
<script src="{% static 'js/forms.js' %}"></script>
<script src="{% static 'js/validador.js' %}"></script>
{% endblock %}
</body>
</html>

cadastro/templates/cadastro/homelider.html
<!DOCTYPE html>


<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Raízes da Educação</title>
    
    {% load static %}
    <!-- Usando a tag Django static para o favicon -->
    <link rel="icon" href="{% static 'img/logo.png' %}">
    <!-- Usando a tag Django static para o CSS -->
   
</head>
<body>
    <header class="superfície">
        <div class="interface">
            <div class="logo">
               <a href="#"> <img src="{% static 'img/logo.png' %}" alt="Logo da Raízes da Educação"></a>
            </div>

            <nav class="menu-desktop">
                <ul>
               
                </ul>
            </nav>
        </div><!--interface-->
    </header>
    

cadastro/templates/cadastro/listar_usuarios.html
{% block title %}Listagem de Clientes{% endblock %}

{% block content %}
    <h1>Clientes Cadastrados</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Email</th>
                <th>CEP</th>
                <th>Rua</th>
                <th>Bairro</th>
                <th>UF</th>
                <th>Complemento</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for usuario in usuarios %}
            <tr>
                <td>{{ usuario.id }}</td>
                <td>{{ usuario.nome }}</td>
                <td>{{ usuario.email }}</td>
                <td>{{ usuario.cep }}</td>
                <td>{{ usuario.rua }}</td>
                <td>{{ usuario.bairro }}</td>
                <td>{{ usuario.uf }}</td>
                <td>{{ usuario.complemento }}</td>
                <td>
                    <a href="{% url 'editar_usuario' usuario.id %}" class="btn btn-editar">Editar</a>
                    <a href="{% url 'excluir_usuario' usuario.id %}" class="btn btn-excluir">Excluir</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}